name          'puppet-tombooth'
version       '0.0.1'
source        'UNKNOWN'
author        'Tom Booth'
license       'MIT'
summary       'Collection of bits and bobs'
description   'UNKNOWN'
project_page  'https://github.com/tombooth/puppet-tombooth'

dependency 'puppetlabs/stdlib', '>= 3.0.0'
